# Generated by Django 4.1 on 2022-08-29 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleWatcher', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scalewatcher',
            old_name='reading',
            new_name='reading1a',
        ),
        migrations.RenameField(
            model_name='scalewatcher',
            old_name='title',
            new_name='title1a',
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='reading1b',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='reading2a',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='reading2b',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='title1b',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='title2a',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='scalewatcher',
            name='title2b',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
