# Generated by Django 4.1 on 2022-08-30 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleWatcher', '0003_rename_title1a_scalewatcher_scale_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='scalewatcher',
            old_name='reading',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='scalewatcher',
            old_name='Scale',
            new_name='title',
        ),
    ]
