# Generated by Django 4.1 on 2022-08-30 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ScaleWatcher', '0004_rename_reading_scalewatcher_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scalewatcher',
            name='line',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
